global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'beatdock-bot'
    static_configs:
      - targets: ['bot:9090']
    scrape_interval: 10s
    metrics_path: '/metrics'