{
 "title": "Bot Metrics",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Discord Groups",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    { "expr": "discord_guilds_count", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Active Bot Players",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "active_players_count", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Commands executed",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 10, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "commands_executed_total{command=\"play\"}",
     "legendFormat": "{{command}}"
    },
    {
     "expr": "commands_executed_total{command=\"pause\"}",
     "legendFormat": "{{command}}"
    },
    {
     "expr": "commands_executed_total{command=\"skip\"}",
     "legendFormat": "{{command}}"
    },
    {
     "expr": "commands_executed_total{command=\"shuffle\"}",
     "legendFormat": "{{command}}"
    },
    {
     "expr": "commands_executed_total{command=\"queue\"}",
     "legendFormat": "{{command}}"
    },
    {
     "expr": "commands_executed_total{command=\"clear\"}",
     "legendFormat": "{{command}}"
    },
    {
     "expr": "commands_executed_total{command=\"back\"}",
     "legendFormat": "{{command}}"
    },
    {
     "expr": "commands_executed_total{command=\"nowplaying\"}",
     "legendFormat": "{{command}}"
    },
    {
     "expr": "commands_executed_total{command=\"stop\"}",
     "legendFormat": "{{command}}"
    }
   ]
  },
  {
   "title": "Queues played",
   "type": "stat",
   "gridPos": { "h": 8, "w": 8, "x": 10, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "songs_played_total{source=\"playlist\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Song Search Time",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 10, "x": 0, "y": 16 },
   "targets": [
    { "expr": "search_duration_seconds_count", "legendFormat": "{{app}}" }
   ]
  },
  {
   "title": "Single Songs Played",
   "type": "stat",
   "gridPos": { "h": 7, "w": 8, "x": 10, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "songs_played_total{source=\"single\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Discord Users",
   "type": "stat",
   "gridPos": { "h": 5, "w": 7, "x": 0, "y": 23 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "discord_users_count", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Discord Guild Count",
   "type": "stat",
   "gridPos": { "h": 5, "w": 7, "x": 7, "y": 23 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "discord_guilds_count", "legendFormat": "__auto" }
   ]
  }
 ]
}